//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniOBS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ders
    {
        public Ders()
        {
            this.OgrenciDers = new HashSet<OgrenciDers>();
            this.OgrenciNot = new HashSet<OgrenciNot>();
        }
    
        public int DersID { get; set; }
        public string DersAd { get; set; }
    
        public virtual ICollection<OgrenciDers> OgrenciDers { get; set; }
        public virtual ICollection<OgrenciNot> OgrenciNot { get; set; }
    }
}
